### ISSUE TITLE
Improve error messages

### ISSUE THREAD

**Issue by robertovclopes** [Stability-AI/REST-API#12]
I'm testing the API in Postman, but I'm getting a 500:

```
{
    "name": "fault",
    "id": "LyMu4toe",
    "message": "image: unknown format",
    "temporary": false,
    "timeout": false,
    "fault": true
}
```

Some messages are already verbose enough, but I couldn't figure out what's the problem this time.

Has anyone also experienced this error?

**Comment by todd-elvers** [comment]
We've deployed `v1beta` and with those changes came a big improvement to error handling.  Hopefully the error messages will be clearer going forward.  I'll leave this issue open for a week or so for feedback.
