### ISSUE TITLE
Every time I make a request with the same keyword, it returns the same image

### ISSUE THREAD

**Issue by sunjujava** [Stability-AI/REST-API#20]
Hello, I used your Rest API to generate images and found an issue. Every time I make a request with the same keyword, it returns the same image. However, on your official demo page, different images are returned for the same keyword each time. What is the reason for this difference? The API address is: [https://api.stability.ai/v1/generation/{engine_id}/text-to-image].

**Comment by johnsabath** [comment]
Are you using the same value for the `seed` parameter on each request?  If so, try omitting it, or setting it to a random value each time.
