### ISSUE TITLE
SDXL model, style selection params in the API

### ISSUE THREAD

**Issue by lihaooo** [Stability-AI/REST-API#21]
Is it possible to use the dreamstudio function, SDXL model and style selection, in the API?

**Comment by kopyl** [comment]
I would also like to know this. Need this model via API so badly.

And also:

1. When will its weights be released or at least how can we figure out when they do? Is there any blog/digest/waitlist to which we can subscribe?
2. Is it possible to use those "styles" with Diffusers and/or AUTOMATIC1111 WebUI?

**Comment by kopyl** [comment]
From Team DreamStudio <dreamstudio@stability.ai>:

> At the moment SDXL is not available via our API. Once we make it available however, we will be noting it in the Release Notes section of our Platform site. 

And

> At the moment we aren't supporting the usage of styles in our API, but when we do we'll be sharing that update in the Release Notes section of Platform as can be found here: https://platform.stability.ai/docs/release-notes 
While the SDXL beta model will be open sourced in the future, we do not currently have a release date available for when we will be releasing the model weights.

**Comment by johnsabath** [comment]
SDXL is now available via the REST API.

Styles will be coming soon as well.

**Comment by geosemaan** [comment]
> SDXL is now available via the REST API.
> 
> Styles will be coming soon as well, possibly next week.

I can't see anything in the documentation, nor the release notes.

What's the model's name?

**Comment by johnsabath** [comment]
That's correct, `stable-diffusion-xl-beta-v2-2-2` is the SDXL Beta model

These are currently supported resolutions for SDXL.  We're still working on optimizing it for other resolutions, and will unlock those options in the future.

```
  - width: 512
    height: 512
  - width: 768
    height: 512
  - width: 512
    height: 768
  - width: 640
    height: 512
  - width: 512
    height: 640
  - width: 896
    height: 512
  - width: 512
    height: 896
```

**Comment by geosemaan** [comment]
Thank you for the reply. Do you think you'll enable 1024x1024 at some point?

**Comment by johnsabath** [comment]
> Thank you for the reply. Do you think you'll enable 1024x1024 at some point?

I'm not sure, but I can ask the inference team what their plans are.

Also, style presets are now available in REST:
![image](https://user-images.githubusercontent.com/2905020/232567100-56ab15f1-fd3a-4e04-867a-2e377841fc32.png)

**Comment by kopyl** [comment]
@johnsabath is it possible to use the older SDXL models?

**Comment by brianfoody** [comment]
@johnsabath can I use style preset through the grpc api?
